/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#ffe084',
        error: '#ba1a1a',
        'surface-container-low': '#edf4ff',
        'surface-container-highest': '#d1e4fb',
        background: '#f7f9ff',
        'on-primary-fixed': '#351000',
        'secondary-container': '#fed023',
        'primary-fixed-dim': '#ffb595',
        'on-secondary': '#ffffff',
        'on-background': '#091d2e',
        'on-secondary-fixed': '#231b00',
        surface: '#f7f9ff',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#203243',
        'secondary-fixed-dim': '#eec209',
        'on-tertiary-fixed': '#00210c',
        'on-tertiary-container': '#f6fff4',
        'surface-tint': '#a23f00',
        'inverse-primary': '#ffb595',
        'surface-bright': '#f7f9ff',
        tertiary: '#006a35',
        'on-error-container': '#93000a',
        outline: '#8c7166',
        'on-secondary-fixed-variant': '#574500',
        'error-container': '#ffdad6',
        secondary: '#735c00',
        'on-secondary-container': '#6f5900',
        'tertiary-container': '#008645',
        'on-primary-fixed-variant': '#7c2e00',
        'surface-container-high': '#d9eaff',
        'on-tertiary-fixed-variant': '#005228',
        'primary-container': '#c64f00',
        primary: '#9e3d00',
        'surface-container': '#e3efff',
        'on-primary': '#ffffff',
        'outline-variant': '#e0c0b2',
        'surface-variant': '#d1e4fb',
        'tertiary-fixed-dim': '#61de8a',
        'tertiary-fixed': '#7efba4',
        'inverse-on-surface': '#e8f2ff',
        'primary-fixed': '#ffdbcd',
        'on-surface-variant': '#594238',
        'on-surface': '#091d2e',
        'on-error': '#ffffff',
        'surface-dim': '#c9dcf3',
        'on-primary-container': '#fffbff',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '40px',
        md: '24px',
        'margin-desktop': '48px',
        base: '8px',
        'margin-mobile': '16px',
        xs: '4px',
        gutter: '24px',
        xl: '64px',
        sm: '12px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'title-md': ['Montserrat', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
